'use client';
import { useState } from 'react';
import { Aperture, Plus } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { type Post, imageUrl } from '@/lib/post-shared';
import { demoPhotos, demoJournals } from '@/lib/demo';
export default function Gallery({posts,error}:{posts:Post[];error:string}){
 const [selected,setSelected]=useState<Post|null>(null);
 const photos=posts.filter(p=>p.kind==='photo'),journals=posts.filter(p=>p.kind==='journal');
 const photoList=photos.length?photos:demoPhotos,noteList=journals.length?journals:demoJournals;
 return <div className="site"><header className="site-header"><a className="brand" href="/moments" aria-label="Photo journal homepage"><Aperture size={23}/><span>Moments</span><small>JERRY'S JOURNAL</small></a><nav aria-label="Main navigation"><a href="#photography">Photography</a><a href="#journal">Journal</a><a href="/">Home</a></nav><a href="/studio" className="write-link"><Plus size={15}/><span>New moment</span></a></header>
 <main><section className="intro"><div><p className="eyebrow">A PERSONAL COLLECTION OF MOMENTS</p><h1>Notice life.<br/><span>Keep moments.</span></h1></div><div className="intro-side"><p>I'm Jerry.<br/>A collection of photographs and words,<br/>for the moments I want to remember.</p><span className="tiny-label">PHOTOGRAPHY & EVERYDAY LIFE</span></div></section>
 {error?<div className="unavailable" role="alert">{error}<button onClick={()=>location.reload()}>Reload</button></div>:<><section id="photography" className="photo-section"><div className="section-heading"><h2>Photography <em>Moments</em></h2><span>{photos.length?String(photos.length).padStart(2,'0')+' moments':'Sample photographs'}</span></div><div className="photo-grid">{photoList.map((p,i)=><button className={'photo-card photo-'+i%3} key={p.id} onClick={()=>setSelected(p)}><div className="photo-frame"><img src={imageUrl(p)} alt={p.title} loading={i===0?'eager':'lazy'}/><span className="view-label">View photograph</span>{p.demo&&<span className="demo-label">Sample photo</span>}</div><div className="photo-caption"><div><h3>{p.title}</h3><p>{p.location||'Everyday life'}</p></div><span>{p.taken_at.replaceAll('-','.')}</span></div></button>)}</div></section>
 <section id="journal" className="journal-section"><div className="section-heading"><h2>Journal <em>Notes</em></h2><span>A few words beyond the photographs</span></div><div className="journal-grid">{noteList.map(p=><button className="journal-card" key={p.id} onClick={()=>setSelected(p)}><div className="note-meta"><time>{p.taken_at.replaceAll('-','.')}</time><span>{p.demo?'Sample entry':p.location||'Journal entry'}</span></div><h3>{p.title}</h3><p>{p.body}</p><span className="read-label">Read entry <span>＋</span></span></button>)}</div></section></>}
 <section id="about" className="about-section"><span className="about-mark">J.</span><div><p className="eyebrow">BEHIND THE MOMENTS</p><h2>Hi, I'm Jerry.</h2><p>I enjoy photography and keeping a journal.<br/>Here are the places I see and the ordinary days worth remembering.</p></div><div className="about-sign">Keep noticing.<br/><span>Keep collecting.</span></div></section></main>
 <footer><a className="footer-brand" href="/moments">Moments <span>JERRY'S JOURNAL</span></a><p>© {new Date().getFullYear()} Jerry · Photography & Journal</p><a href="/studio">Studio</a></footer>
 <Dialog open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><DialogContent className={'detail-dialog '+(selected?.kind==='photo'?'photo-dialog':'')}><DialogTitle className="detail-title">{selected?.title}</DialogTitle><DialogDescription className="detail-meta">{selected?.taken_at.replaceAll('-','.')} · {selected?.location||'Journal'}{selected?.demo?' · Sample content':''}</DialogDescription>{selected?.image_key&&<img className="detail-image" src={imageUrl(selected)} alt={selected.title}/>}<p className="detail-body">{selected?.body}</p>{selected?.source&&<small className="source-note">Sample photograph by: {selected.source}</small>}</DialogContent></Dialog>
 </div>;
}
